# -*- coding: utf-8 -*-
"""cleaning_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUEydY7Uj5bK03zoUaCUIv3010J09Ee_

Load the data & Print firat 5 rows :
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("prevek18/ames-housing-dataset")

print("Path to dataset files:", path)

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

def load_data(path):
    return pd.read_csv(path)

def show_head(df):
    return df.head(5)

"""Check the shape:"""

def get_shape(df):
    return df.shape

"""Get the info:"""

def get_info(df):
    df.info()

def fix_data_types(df):
    df["MS SubClass"] = df["MS SubClass"].astype(str)
    df["Overall Qual"] = df["Overall Qual"].astype(float)
    return df

"""Handle missing values:

I decide to chose.fillna(), because:


*   deleting missing values would remove many rows, and I want to keep as much data as possible .

"""

def handle_missing_values(df):

    numeric_cols = df.select_dtypes(include=np.number).columns
    df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

    categorical_cols = df.select_dtypes(include="object").columns
    df[categorical_cols] = df[categorical_cols].fillna("Unknown")

    return df

"""Remove duplicates:"""

def remove_duplicates(df):
    print("Number of duplicates:", df.duplicated().sum())
    df = df.drop_duplicates()
    return df

"""Spot outliers:"""

def plot_boxplot(df):
    df["SalePrice"].plot.box()
    plt.title("Boxplot of SalePrice")
    plt.show()

"""Handle outliers"""

def handle_outliers(df):
    if "SalePrice" in df.columns:
        upper_limit = df["SalePrice"].quantile(0.99)
        df["SalePrice"] = df["SalePrice"].clip(upper=upper_limit)
    return df

"""Final Checks:"""

def clean_data(path):

    df = load_data(path)

    print("Shape before cleaning:", df.shape)

    df = fix_data_types(df)
    df = handle_missing_values(df)
    df = remove_duplicates(df)
    df = handle_outliers(df)

    print("Shape after cleaning:", df.shape)

    assert df.isnull().sum().sum() == 0
    assert df.duplicated().sum() == 0
    assert (df["SalePrice"] > 0).all()

    return df

cleaned_df = clean_data(path + "/AmesHousing.csv")

print(cleaned_df.shape)
print(cleaned_df.isnull().sum().sum())
print(cleaned_df.duplicated().sum())

cleaned_df = clean_data("/kaggle/input/ames-housing-dataset/AmesHousing.csv")